
spring:
  application:
    name: eureka-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Liyinzuo/colud-config
          search-paths: config-1
          username: Liyinzuo
          password: lyzlikebeef@163.com

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/